[package]
name = "leader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
plonky2 = { workspace = true }
plonky2_evm = { workspace = true }
clap = { workspace = true }
protocol_decoder = { workspace = true }
plonky_block_proof_gen = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
paladin-core = { workspace = true }
dotenvy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ethers = { workspace = true }

itertools = "0.11.0"
eth_trie_utils = { git = "https://github.com/0xPolygonZero/eth_trie_utils.git", rev = "e9ec4ec2aa2ae976b7c699ef40c1ffc716d87ed5" }
hex = "0.4.3"
serde_json = "1.0.108"

# Local dependencies
ops = { path = "../ops" }
common = { path = "../common" }
